### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by vrt0r** [r-kitek/cordova-team-viewer#2]
Hello, i get a Error when i try to compile for iOS with XCode 8:
"_SecItemDelete", referenced from:
1>        l6325 in ScreenSharingSDK(libScreenSharingSDK.a-armv7-master.o)
1>  ld: symbol(s) not found for architecture armv7
1>clang : error : linker command failed with exit code 1 (use -v to see invocation)

In the build.xcconfig i have ENABLE_BITCODE = NO

**Comment by architechnyc** [comment]
Hi @vrt0r, thank you for your response. I'm working on this right now

**Comment by architechnyc** [comment]
Resolved in https://github.com/r-kitek/cordova-team-viewer/releases/tag/v0.1.1

**Comment by vrt0r** [comment]
Update:
It's working. I had to add iOS Target Version 7 in the Config.xml
After that it was working in iOS also. Thanks.

---

Hello,

thanks for taking the time @architechnyc , im sorry, but i tried with the version you provided and still got the same error.
[error.txt](https://github.com/r-kitek/cordova-team-viewer/files/479440/error.txt)

If you have an idea or need more info just write.  The remote build server is El Capitan with XCode Version 8.

I just created a new simple testproject from VS2015  (Blank Apache Cordova Project), added the plugin and added a link to start teamviewer. Android still works without problems.

**Comment by architechnyc** [comment]
@vrt0r what target did you have before?

**Comment by vrt0r** [comment]
The Field was empty (standard when creating a new project). 
I read somewhere about a problem with the libz.dylib and they say they only got it if the target version is lower then 7, so i searched and found it under iOS Settings in VS. Im not sure, but i have the feeling this option wasn't even there before i installed the vs2015 cordova update.

**Comment by architechnyc** [comment]
Ok. Thanks for the info. Seems like I need to add this to README
